### ISSUE TITLE
save color themes

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#10]
by now is posible to change the colors(?), speed ans font size, but wil be great if all these changes are saved as a "theme", any user can set the teleprompter just selecting they theme from a list, export and import "theme files" or just save it in local

**Comment by manifestinteractive** [comment]
I am not sure if you are stating that the settings are not being stored correctly, or you are asking for a new feature.

It sounds like you are asking for a way to export the setting so they can be used on multiple projects.  Is this what you are asking for ?

**Comment by snchzantonio** [comment]
option two: asking for a new feature.

think "theme" like in a code editor (zenburn, monokai, bespin, etc)


One of my friends works on the radio, in the station there is an instance of your teleprompter running and has another in his house, he is very upset because in his house has interface colors that he likes and in the station someone always change it. He spends time configuring everything as he likes, so he asked me if it is possible to take the configuration from one instance of the teleprompter to another


From there came the idea of ​​having themes for the interface that can be imported and exported

**Comment by manifestinteractive** [comment]
This will be fixed in the next release ( v1.2.0 )

**Comment by manifestinteractive** [comment]
This is now live in production via https://github.com/manifestinteractive/teleprompter/releases/tag/v1.2.0
