### ISSUE TITLE
one text multiple teleprompters plus remote control

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#11]
show the same text in diferent instances, the changes made in one get sync  in others, plus an operator dashboard/master control to set some configurations (like disallow clients to change the text, themes, text , bla bla  bla )

i think in two aproaches:

multi monitor: no lan, every intance comunicate with each other ready and writing in a localdatabase(localstorage) o web socket or service worker, dont really sure

multiple devices: lan required, like the multi monitor but in a lan

**Comment by manifestinteractive** [comment]
This is not possible with this software and would require writing an entirely different application to support it that uses web sockets and service workers.  As an open source project, you are certainly entitled to fork this code and go down that road, but that is not a direction I want to take this project.
