### ISSUE TITLE
0 speed scroll

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#12]
when the speed is set to 0 the scroll go on, but should stop

**Comment by manifestinteractive** [comment]
I have no idea what you are stating here :(  Sorry

Can you add steps to duplicate ?

**Comment by snchzantonio** [comment]
sure: 
press play
slide speed to 0
 the text still scroll
 0 speed is like "no move" 
the expected behavior is for the text to stop as if the pause button is pressed

**Comment by manifestinteractive** [comment]
This will be fixed in the next release ( v1.2.0 )

**Comment by manifestinteractive** [comment]
This is now live in production via https://github.com/manifestinteractive/teleprompter/releases/tag/v1.2.0
