### ISSUE TITLE
remote control

### ISSUE THREAD

**Issue by aaronpk** [manifestinteractive/teleprompter#14]
This is really great! I've been looking for a straightforward teleprompter app. Would you be open to a PR that enables remote control of the prompter? I've had situations where I need to remotely control the speed or pause the prompter next to the camera. 

I was thinking about writing a small server-side component to coordinate the viewer with the control computer. I'd like to be able to see a preview of the main screen from an iPhone screen, and be able to do basic controls like pause/speed/scroll. Is this something you'd be interested in including in this package? If not, I'm happy to just do it myself under a new name. Thanks!

**Comment by manifestinteractive** [comment]
@aaronpk open to any PR that makes this a better experience for the users ;)

**Comment by aaronpk** [comment]
Hey there, just wanted to check if you've had a chance to look at my PR that adds this feature! Thanks!

**Comment by aaronpk** [comment]
Huge thanks for writing a better version! 

https://github.com/manifestinteractive/teleprompter/pull/17#issuecomment-507002307
