### ISSUE TITLE
Escape key not working after editing

### ISSUE THREAD

**Issue by donniebreve** [manifestinteractive/teleprompter#15]
It seems like after editing content the keyboard shortcuts become unavailable, most importantly the escape key.

Ideally, after editing the user would hit the escape key to go back to 'presentation' mode where the keyboard shortcuts would become available again (space and arrow keys).

**Comment by donniebreve** [comment]
Hope this gets merged soon, thanks for the change.

**Comment by manifestinteractive** [comment]
This will be fixed in the next release ( v1.2.0 )

**Comment by manifestinteractive** [comment]
This is now live in production via https://github.com/manifestinteractive/teleprompter/releases/tag/v1.2.0
