### ISSUE TITLE
Font Style

### ISSUE THREAD

**Issue by tips2fix** [manifestinteractive/teleprompter#18]
Hi this script is very cool , but i was wondering if it will have more option than 100 zoom size put it 200.
no option for making Bold text  or italic 
boldnes level is very nesesary :D

**Comment by seriousm4x** [comment]
also text color and line height would be nice

**Comment by manifestinteractive** [comment]
This is a plain text editor, so it will not have support for rich text formats.  There is no plan to support this moving forward.
