### ISSUE TITLE
Mirror flip has the text scrolling backwards

### ISSUE THREAD

**Issue by Taapo** [manifestinteractive/teleprompter#2]
Great script - and very useful already. On bug though: when activating the mirror feature, the text is scrolling from bottom to top, it should be reverse ... or maybe I haven't found the right feature?

**Comment by manifestinteractive** [comment]
This has been fixed and is updated on https://promptr.tv

Sorry I missed this ticket, for some reason I do not recall getting a notice that the issue was created on Github.
