### ISSUE TITLE
Dual Scroller/Slider Control for the 'Remote'

### ISSUE THREAD

**Issue by migeru-san** [manifestinteractive/teleprompter#31]
**Will it be possible to add a slider to have more control?**

The + and - buttons are great but it takes so long to adjust when the speaker is going too slow or fast.

or even better a dual-purpose-slider.
That you can select speed or scroll position.

![E3ipXILWUAkuslk](https://user-images.githubusercontent.com/68115458/121610755-b2a93880-ca24-11eb-86a1-208ca291e101.jpg)

Original thread:
https://twitter.com/MigeruSan_/status/1403057503227760643

**Comment by manifestinteractive** [comment]
This will be fixed in the next release ( v1.2.0 )

**Comment by manifestinteractive** [comment]
@migeru-san New Remote Interface that will be coming out in the next release:

![screenshot 2021-06-13 at 3 51 13 AM](https://user-images.githubusercontent.com/508411/121799555-cc9c7400-cbfa-11eb-958e-2c275de4ee6d.png)

- [X] New Slider that sends real time data as you drag
- [X] Select list above slider to switch between controlling SPEED, FONT & SCROLL
- [X] I liked your layout for buttons at top, as it solved a problem for adding the other controls, so now I can get those in as well

Probably still another week out before this gets merged and deployed ( at least ) ... but making good progress.

**Comment by manifestinteractive** [comment]
This is now live in production via https://github.com/manifestinteractive/teleprompter/releases/tag/v1.2.0
