### ISSUE TITLE
A popup after clicking the Shutdown/quit button

### ISSUE THREAD

**Issue by migeru-san** [manifestinteractive/teleprompter#32]
Self-explanatory :P

![image](https://user-images.githubusercontent.com/68115458/121611888-51cf2f80-ca27-11eb-9004-bb992fb59134.png)

**Comment by manifestinteractive** [comment]
This will be fixed in the next release ( v1.2.0 )

**Comment by manifestinteractive** [comment]
This is now live in production via https://github.com/manifestinteractive/teleprompter/releases/tag/v1.2.0
