### ISSUE TITLE
cookie storage dont works

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#4]
hi again, for some reason the cookie storage feature dont works, 
Have you thought about replacing it with other technology like localstorage?

**Comment by manifestinteractive** [comment]
Any change you have any error logs or messages being shown that you can share here ?

**Comment by manifestinteractive** [comment]
Also, I need to know details like what browser and operating system you are using.  Plus version numbers of both.  I need to know what you were using to make sure I can test this properly.

**Comment by snchzantonio** [comment]
my apologies, I`m newbie in this:

i dont make any changes to the save feature (even touch it)

No message appears on the console

windows 10 pro 64bit
chrome 55
keyboard layout: ESP-ES (Spanish, Venezuela)

**Comment by aaronpk** [comment]
Cookies have a maximum size. I've noticed that when I paste in a large document, it just silently fails. I'm guessing that's what's happened here. 

I'm considering switching this to use LocalStorage to store the text instead.

**Comment by manifestinteractive** [comment]
@aaronpk localStorage would be pretty sweet.  It was still not 100% covered 4 years ago when I started this, but it is now.  Pretty much all devices should support this, including mobile ( which was the main one that was giving me troubles for support in the beginning ).

**Comment by aaronpk** [comment]
Browser support is great now! https://caniuse.com/#feat=namevalue-storage

I'll work on a PR for this separately then. I'll just use the LocalStorage API directly to avoid pulling in a new library.

**Comment by manifestinteractive** [comment]
This was resolved a bit ago and never closed.  v1.1.0 updated to use Local Storage and port over any existing cookies that users might have had.
