### ISSUE TITLE
Remote Control feature broken on promptr.tv?

### ISSUE THREAD

**Issue by stefanbaur** [manifestinteractive/teleprompter#49]
Hi,

When I click on the remote control icon (to the right of the font/speed sliders) on promptr.tv, nothing happens.
I'm pretty sure this button was functional in the past.

Happens with Chromium Version 108.0.5359.71 as well as Firefox 108.0 on Linux, so I doubt it's a browser issue.

Could you please look into it?

Kind Regards,
Stefan Baur

**Comment by amazighdotmobi** [comment]
Hi, 
Same problem for me ....

**Comment by manifestinteractive** [comment]
@stefanbaur and @amazighdotmobi looks like the remote server crashed so I restarted it.
