### ISSUE TITLE
Remote Control feature broken

### ISSUE THREAD

**Issue by amazighdotmobi** [manifestinteractive/teleprompter#53]
Excuse me for insisting Peter but for me, remote control does not work with version 1.2.0. I downloaded and installed version 1.1.1 and it works perfectly.
Kind regards

**Comment by manifestinteractive** [comment]
Are you saying it is not working on the website? Because that's what this repo is for.  The website version is running right now with version 1.2.0 and the remote is working correctly ( I just tested it ).

If you are doing a custom install, can you please provide any errors you are seeing? I can't do much with "it's not working" kind of messages, need to know details, e.g. what kind of computer you are using, how you tried to start the server, what error you got when you tried it.

I am assuming you are following the documentation as well, so let me know if you deviated from anything in https://github.com/manifestinteractive/teleprompter/blob/master/DEVELOPERS.md that documents how to start the server.

**Comment by amazighdotmobi** [comment]
Sorry Peter, I now understand my mistake. Indeed I had not consulted the DEVELOPERS.md document for version 1.2.0 and I will follow the procedure described. Thanks to you.

**Comment by manifestinteractive** [comment]
Thanks, admittedly this project is getting a LOT more developers recently that want to spin up their own versions, so I need to do a better job of making that easier.  The original scope of this project was just to make it available at https://promptr.tv and allow others to help build that website out :)

But over the last couple of years, it seems there is interest from a few folks on being able to run this themselves.

I have a version I am working on that lets you actually run this as an Electron app that should be coming out this year.  It would actually allow you to overlay the teleprompter over any other app, so you can read through the prompter.

So when that version comes out, I will have a BUNCH more docs for developers like yourself on how to spin up all the services needed to run this from your computer.  This new version means you can install it as a native app and do a lot more powerful things with it.

Lot's of great ideas coming from the community, and learning all sorts of ways people are using this tool that I never would have imagined.

I'll keep this ticket open for a bit, and please let me know if that documentation gets you up and running.  If it does, we can close this ticket.  If things are still broken for you, just give me the info I requested and I can take a look.

Tomorrow I will work on adding templates for GitHub that make collecting this information easier.  When I first made this repo, those features in GitHub did not exist, but now they could help some folks out, and get me the info I need, so I will get those added.

**Comment by amazighdotmobi** [comment]
Thank you for your reply Peter. Indeed, I am not a developer but only a bit of a technophile. That's why I didn't understand the installation method. It is more a problem of competence on my side than a problem of documentation :-)

For information, I use your prompter with students to help them in different speaking situations. The planned developments seem to me very interesting for a better adaptation to the different contexts of schools. In any case, thank you for your work, which we use regularly. 

I will follow future developments with interest.

**Comment by amazighdotmobi** [comment]
I have installed teleprompter on my computer with your documentation and it works fine. However, I am having problems with an installation on a Vitual Private Server that I administer via PLESK. I think the problem comes from there because I have less flexibility than a command line installation. I will continue my tests. So we can close this ticket. Thanks to you and happy new year 2023
