### ISSUE TITLE
[Bug]: Text not displayed

### ISSUE THREAD

**Issue by takuyaliu** [manifestinteractive/teleprompter#65]
### Contact Details

783395107@qq.com

### What happened?

Text not displayed, even if I unzip the file again, it will still be the same.
![1728636392223](https://github.com/user-attachments/assets/af3eaf9d-e74c-4350-a13b-95deb0033420)

### What type of browser are you seeing the problem on?

Chrome, Microsoft Edge

### What type of Operating System are you seeing the problem on?

Windows

**Comment by manifestinteractive** [comment]
Please see the Developer documentation on how to run this program on your computer:

https://github.com/manifestinteractive/teleprompter/blob/develop/DEVELOPERS.md

You cannot simply open the Zip File as this is a web application that requires you to run it using NodeJS.

That documentation covers the details on how to do this.  If your computer is not setup to run development software, there is also an option to use [Docker Desktop](https://www.docker.com/products/docker-desktop/) via this section:

https://github.com/manifestinteractive/teleprompter/blob/develop/DEVELOPERS.md#running-as-a-docker-container

**Comment by manifestinteractive** [comment]
Removing the `Bug` label as this was not a bug in the software, so nothing we can fix here.
