### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#7]
i`m not much proficient in JS, so it´s posible to make a code revision for improve the performance enough to use the teleprompter in cheap android devices ?

i have a no brand table (1gb ram, 4x1.2ghz cores, without standard support for android chrome or google play) that is very popular in my country (Venezuela) and a notebook (1x1.1ghz intel core, 2gb ram) very popular too and want to make them the commom devices to run the teleprompter (because they popularity) but the teleprompter gets stuck by seconds o make little jumps when scrolling some text (538 words in 97 lines)

so, i want to make a code performance leaks hunting, if you can give me some tips or a place to start I appreciate it a lot

**Comment by manifestinteractive** [comment]
The issue on older devices is GPU performance.  This project is literally moving LARGE quantities of text with a custom overlay.  This means the browser has to repaint each pixel that changes during scroll.  Modern devices use hardware acceleration to improve performance.  The only solution that would benefit devices without hardware acceleration is to literally use a brand new way of rendering everything.  Even then, with the large volume of stuff that is moving on the screen, there is not much you can do.  Old devices without dedicated GPU's are just not going to be capable of running a web based app with large moving text that needs to be repainted.

This is a hardware problem, not a software problem.  So for this project, there is nothing that can be done to increase performance on older devices.

**Comment by snchzantonio** [comment]
LARGE quantities of text , jumm :S ... and if they are cut and displayed part by part ?, something like lazy load: the text is divided into parts and one of these parts is shown at a time, when the scroll is to about to finish is added a new section, of course the section that has just been shown is cut it



I do not know how to implement that, but it's a start
