### ISSUE TITLE
upload file and other tweaks

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#8]
This was the first thing they asked me when I showed the teleprompter to my friends: can i upload files?

I implement it in my fork already, plus charsets encodings, concat text of uploaded files or completely replace it

and soon will be able to color paragraphs to make posible to be used by several people at once (one color for person) and add text in markdown (currently only no format text is allowed)

any way, maybe you would like to add those features to the original branch, so I comment them so you know
the overlay toggleable idea (pull request #1 ) is really good, take a look and merge it if you like it :)

**Comment by snchzantonio** [comment]
i almost forget: add buttons to increase/decrease speed and jump up in the text

**Comment by manifestinteractive** [comment]
I am open to an update that allows uploading TXT files, however, I do want to keep the focus of this project to a standalone application with no back-end requirements ( such as websockets, server side processing, etc ).

I have not had a chance to look at the PR yet and actually just discovered it was there a few days ago.  For some reason, I never got the notice from Github when it was originally created, and this project has pretty low activity, so I had not checked it.

**Comment by snchzantonio** [comment]
i will make a new brach to pull the file upload and uptated libs, Leaving untouched the others things


About the low activity, it is true, it should be the only one that is currently reviewing the project, but I still think it has a lot of potential, teleprompters does not seem to be very popular in github, the project with the most star only has 100 and 3 Years outdated( https://github.com/soxofaan/scrollocue ) and this one has 3 starts and is quite complete(https://github.com/imaginaryfilms/Teleprompter-Core)


I suppose it does not affect me because I have gotten some users, several of my friends are announcers, local animators and actors, together sum about 100 perosons who use this teleprompter and that entertains me a lot, I learned a lot of java script reviewing it and I guess That is: learn and use that knowledge to benefit others, to make your life a little better (even if they are only 100 people and a newbie in js)

**Comment by manifestinteractive** [comment]
No plans to implement this feature.
