### ISSUE TITLE
setup shortcuts

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#9]
to be able configure multiple pointers devices without changing the code directly

**Comment by manifestinteractive** [comment]
huh ?  Not sure what you are asking for here.

**Comment by snchzantonio** [comment]
new feature: Configure the keyboard shortcuts so that the user can choose which key to speed up the text, increase the size of the letters and other.


That way if someone has one of those fanzy wireless pointers ( http://www.bestbuy.com/site/logitech-presentation-pointer-black/9664127.p?skuId=9664127 ) can use it to manipulate the teleprompter

**Comment by manifestinteractive** [comment]
No plans to implement this feature, though we will be adding keyboard support for remotes in the next release ( v1.2.0 )
